spring:
  application:
    name: AIDemo
  ai:
    retry:
      max-attempts: 2
    openai:
      api-key: ${OPENAI_API_KEY}
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true
