spring:
  application:
    name: AIDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        embedding:
          api-key: ${GOOGLE_API_KEY}
  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      schema-locations:
        - classpath:init/schema.sql
      mode: always
      
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true